### ISSUE TITLE
Transcription progress

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/mab-lunar-lander#1]
Logging progress here.  Page numbers are those in the PDF; check box for allocation.

- [x] Page 1
- [x] Page 2
- [x] Page 3
- [x] Page 4
- [x] Page 5
- [x] Page 6
- [x] Page 7
- [x] Page 8
- [x] Page 9
- [x] Page 10
- [x] Page 11
- [x] Page 12
- [x] Page 13
- [x] Page 14
- [x] Page 15
- [x] Page 16
- [x] Page 17
- [x] Page 18
- [x] Page 19
- [x] Page 20
- [x] Page 21
- [x] Page 22
- [x] Page 23
- [x] Page 24

**Comment by larsbrinkhoff** [comment]
@drboone grabbed pages 1-6.

**Comment by larsbrinkhoff** [comment]
I pushed page 7 as listing.txt.  I didn't bother with exact whitespace... yet.

**Comment by larsbrinkhoff** [comment]
I'm putting in form feed characters as indicated by listing page numbers.  I.e. "PAGE 10" and "PAGE 10-1" have no ^L between them.

**Comment by larsbrinkhoff** [comment]
I'm putting in form feed characters between listing pages.

Note that the future reconstructed source file should not have ^L in all those places.  I.e. listing "PAGE 10" and "PAGE 10-1" should be one source page.

**Comment by drboone** [comment]
From the standpoint of the later merge, I wonder if it would be easier to have each photo be its own file?

**Comment by larsbrinkhoff** [comment]
Don't worry about it.  I'll cut and paste as necessary.

**Comment by larsbrinkhoff** [comment]
All done!
